# Keepalived BACKUP 설정 - cp2, cp3 전용
# cp2: priority 90 / cp3: priority 80 으로 변경하여 사용
# VIP: 192.168.1.100

vrrp_instance VI_1 {
    state BACKUP
    interface eno1
    virtual_router_id 51
    priority 90        # cp3는 이 값을 80으로 변경
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1234
    }
    virtual_ipaddress {
        192.168.1.100/24
    }
}
